version: '3'
services:
  authentication-service:
    build: ./authentication
    container_name: authentication
    ports:
      - "7070:7070" # Use spaces, not tabs, to indent
    networks:
      -  network
      
      
  mysqldb:
    image: mysql # Use mysql image from docker hub with version 5.7 
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: Deya@12# # Set root password for mysql 
      MYSQL_DATABASE: db1 # Create a database named data_db 
    ports:
      - 3307:3306
    networks:
      -  network 
    volumes:
      - mysql-data:/home/


  
  enter-data-service:
    build: ./enterdata
    restart: on-failure
    ports:
     - "8080:8080" # Use spaces, not tabs, to indent
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db1?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Deya@12#
      SPRING_JPA_HIBERNATE_DDL_AUTO : update
    depends_on:
      - mysqldb 
      - authentication-service
    networks:
      -  network
      -  mongodb_network
      
  mongodb:
    image: mongo
    restart: on-failure
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=analytics # Create a database named mydatabase 

    networks:
      -  mongodb_network    
    volumes:
      - mongo-data:/home/

  mymongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      -  mongodb_network
    volumes:
      - mongo-data:/home/node/app

      
  analysis-service:
    build: ./analysis
    restart: on-failure
    ports:
      - "9797:9797" # Use spaces, not tabs, to indent
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db1?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Deya@12#
      SPRING_JPA_HIBERNATE_DDL_AUTO : update
      SPRING_DATA_MONGODB_HOST: mongodb
    networks:
      - network
      - mongodb_network
    depends_on:
      - mysqldb # The analytics service depends on mysql service
      - mongodb

  show-data-service:
    build: ./showdata
    ports:
      - "9090:9797" # Use spaces, not tabs, to indent
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      AUTHENTICATION_PATH: authentication
    networks:
      -  network
      -  mongodb_network
    depends_on:
      - mongodb
      - mymongo-express
      - authentication-service
      

      
volumes:
  mysql-data: {}
  mongo-data: {}

networks:
  mongodb_network:
  network:


      

